name: Run JS Standard check
on: [push]

jobs:
  standardjs_job:
    name: On push run StandardJS from nodeJS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependenties
        uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build --if-present
        env:
          CI: true
      - uses: actions/checkout@v2
      - name: Running standardJS
        uses: actions/setup-node@v1
      - run: npm run standardJS
        env:
          CI: true